# This is a basic workflow to help you get started with Actions

name: export-to-dev-branch

# Controls when the workflow will run
on:
  # Triggers on demand
  workflow_dispatch:
    inputs:
      branch:
        required: true
      branchToCreate:
        required: false
      solutionName:
        required: true
      commitMessage:
        required: true

jobs:
  export-solution:
    uses: tchinnin/powerplatform-alm-workflows/.github/workflows/export-solution.yml@main
    with:
      solutionName: ${{ github.event.inputs.solutionName }}
    secrets:
      ENV_URL: ${{ secrets.ENV_URL }}
      DATAVERSE_APPID: ${{ secrets.DATAVERSE_APPID }}
      DATAVERSE_SECRET: ${{ secrets.DATAVERSE_SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
  
  unpack-solution-to-branch:
    needs: export-solution
    uses: tchinnin/powerplatform-alm-workflows/.github/workflows/unpack-solution-to-branch.yml@main
    with:
      solutionName: ${{ github.event.inputs.solutionName }}
      branch: ${{ github.event.inputs.branch }}
      branchToCreate: ${{ github.event.inputs.branchToCreate }}
      commitMessage: ${{ github.event.inputs.commitMessage }}